# Generated by scripts/brew-formula.sh. Do not edit by hand.
class Warden < Formula
  desc "Governed data-access runtime for AI agents"
  homepage "https://github.com/Abhishek-Mallick/warden-dist"
  version "0.1.1"
  # Proprietary terms, so no SPDX identifier applies. See LICENSE.md in
  # the distribution repository.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.1/warden_0.1.1_darwin_arm64.tar.gz"
      sha256 "0dcc371a92c668781db9d48815b7f328178d3e8665b06e1642140b580400011c"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.1/warden_0.1.1_darwin_amd64.tar.gz"
      sha256 "3d5569cca87ce841c6e984f66356b509856c9fe2177fcf000857397b11726cbb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.1/warden_0.1.1_linux_arm64.tar.gz"
      sha256 "f18e2e0bf10377b8861dec9760a6b1f04876c9cd07d4054fefc117913559dcf7"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.1/warden_0.1.1_linux_amd64.tar.gz"
      sha256 "1321b282c5437462c28d27f95a655619a366b4a2de125cdac1796c59c84ad454"
    end
  end

  def install
    bin.install "warden"
    bin.install "warden-mcp"
  end

  def caveats
    <<~EOS
      Warden needs a configuration file before it will serve traffic:

        warden serve --config warden.yaml

      A starting point, and the policy language it refers to:
        https://github.com/Abhishek-Mallick/warden-dist#configuration
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/warden version")
    # The shim must refuse to start without an agent identity: a gateway client
    # that silently runs unauthenticated would be worse than one that fails.
    assert_match "WARDEN_AGENT_ID", shell_output("#{bin}/warden-mcp 2>&1", 2)
  end
end
