# Generated by scripts/brew-formula.sh. Do not edit by hand.
class Warden < Formula
  desc "Governed data-access runtime for AI agents"
  homepage "https://github.com/Abhishek-Mallick/warden-dist"
  version "0.1.0"
  # license: add one to the repository and declare it here.

  on_macos do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.0/warden_0.1.0_darwin_arm64.tar.gz"
      sha256 "22e861ef55e03dcaad07cac8f0351b8ad8bf6c972ecf6cee49c25de1fd116f73"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.0/warden_0.1.0_darwin_amd64.tar.gz"
      sha256 "3eba0e1e844819969c3948b0a2247a0ad3909ab67903d5f75ce5293f99058241"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.0/warden_0.1.0_linux_arm64.tar.gz"
      sha256 "0cba0e2d3f7200598a93a6d122cecc95e179b5a29156b3f6eaef703785bdca2a"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.1.0/warden_0.1.0_linux_amd64.tar.gz"
      sha256 "d781c63aaddd429d6c26065be193717848d7f3b11f2a5780922a737eb248e398"
    end
  end

  def install
    bin.install "warden"
    bin.install "warden-mcp"
  end

  def caveats
    <<~EOS
      Warden needs a configuration file before it will serve traffic:

        warden serve --config warden.yaml

      A starting point, and the policy language it refers to:
        https://github.com/Abhishek-Mallick/warden-dist#configuration
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/warden version")
    # The shim must refuse to start without an agent identity: a gateway client
    # that silently runs unauthenticated would be worse than one that fails.
    assert_match "WARDEN_AGENT_ID", shell_output("#{bin}/warden-mcp 2>&1", 2)
  end
end
