# Generated by scripts/brew-formula.sh. Do not edit by hand.
class Warden < Formula
  desc "Governed data-access runtime for AI agents"
  homepage "https://github.com/Abhishek-Mallick/warden-dist"
  version "0.2.0"
  # Proprietary terms, so no SPDX identifier applies. See LICENSE.md in
  # the distribution repository.
  license :cannot_represent

  on_macos do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.2.0/warden_0.2.0_darwin_arm64.tar.gz"
      sha256 "d24e59ffbbc58b2c4c5ebcfa0c4b7005c09fd60307934991db0dc8aa59e2cae6"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.2.0/warden_0.2.0_darwin_amd64.tar.gz"
      sha256 "a4b1d55a0fa0e2e554eddb442a6d401cf8be269a28c7aab08d6677ea393210ab"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.2.0/warden_0.2.0_linux_arm64.tar.gz"
      sha256 "390709c190eca609aca095d3f9e22deee1e1dfddd2bbc308c7810c82c349b9a8"
    end
    on_intel do
      url "https://github.com/Abhishek-Mallick/warden-dist/releases/download/v0.2.0/warden_0.2.0_linux_amd64.tar.gz"
      sha256 "6fd1d24add5327f4ee741d243a02c5eb53d91448c47ba6edd3912905e184ae60"
    end
  end

  def install
    bin.install "warden"
    bin.install "warden-mcp"
  end

  def caveats
    <<~EOS
      Warden needs a configuration file before it will serve traffic:

        warden serve --config warden.yaml

      A starting point, and the policy language it refers to:
        https://github.com/Abhishek-Mallick/warden-dist#configuration
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/warden version")
    # The shim must refuse to start without an agent identity: a gateway client
    # that silently runs unauthenticated would be worse than one that fails.
    assert_match "WARDEN_AGENT_ID", shell_output("#{bin}/warden-mcp 2>&1", 2)
  end
end
